### ISSUE TITLE
el-table--striped shows in white background

### ISSUE THREAD

**Issue by hildingandersspain** [Arattian/element-theme-dark#1]
Hello, first of all thank you for your great theme!
I found two css that I have to change every time that I rebuild my vue app with this theme:

In table.css:
```
.el-table--striped .el-table__body tr.el-table__row--striped td {
    background: #FAFAFA; }
```
I change manually it to #1f3647;

In index.css:
```
.el-table--striped .el-table__body tr.el-table__row--striped td {
    background: #FAFAFA; }
```
Same case. I change it manually to #1f3647;

Could you be so kind to update it? I don't make a pull request since it's quite straightforward.

Thanks in advance!

**Comment by Arattian** [comment]
Fixed [npm](https://www.npmjs.com/package/element-theme-dark).
If you faced another issues with light background please let me know.
I just modified scss file and generated css from that. Some css backgrounds is not configurable from their scss, so it is common to see some light backgrounds that passed build process.
